# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QComboBox, QVBoxLayout, QWidget,QCheckBox
from PyQt5.QtGui import QImage
import numpy as np
import cv2, imutils
import threading
from imutils.video import VideoStream
import pyshine as ps
import time
from calibrate import Calibration
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.vid = None
        self.isLabel = False
        self.dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_7X7_1000)
        self.board = cv2.aruco.CharucoBoard((6,10),0.02,0.01,self.dictionary)
        self.params = cv2.aruco.DetectorParameters()
        self.criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 50, 0.0001)
        self.image = None
        self.default_folder = ''
        self.stopEvent = threading.Event()
        self.calibration = Calibration(cv2,self.default_folder)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 781, 571))
        self.tab1 = QWidget()
        self.tab2 = QWidget()
        self.tabs.addTab(self.tab1, "Camera")
        self.tabs.addTab(self.tab2, "Calibration")

        self.layout_tab1 = QVBoxLayout(self.tab1)
        self.layout_tab2 = QVBoxLayout(self.tab2)

        self.horizontalSlider = QtWidgets.QSlider(self.tab1)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 490, 651, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(100)
        self.layout_tab1.addWidget(self.horizontalSlider)

        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab1)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 520, 651, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_2.setMaximum(100)
        self.layout_tab1.addWidget(self.horizontalSlider_2)

        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(30, 30, 581, 431))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.image))
        self.label.setObjectName("label")
        self.layout_tab1.addWidget(self.label)

        self.checkBox = QCheckBox(self.tab1)
        self.checkBox.setGeometry(QtCore.QRect(130,530,161,31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.stateChanged.connect(self.changeCameraSetting)
        self.layout_tab1.addWidget(self.checkBox)
        
        self.buttonFlag = QtWidgets.QPushButton(self.tab1)
        self.buttonFlag.setGeometry(QtCore.QRect(0,0,30,30))
        self.buttonFlag.setObjectName("buttonFlag")
        self.buttonFlag.setStyleSheet("background-color : red")
        self.buttonFlag.setDisabled(True)
        self.layout_tab1.addWidget(self.buttonFlag)

        self.comboBox = QComboBox(self.tab1)
        self.comboBox.setGeometry(QtCore.QRect(620, 560, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Gaussian Blur")
        self.comboBox.addItem("Bilateral Filter")
        self.comboBox.currentIndexChanged.connect(self.applyFilter)
        self.layout_tab1.addWidget(self.comboBox)

        self.pushButton_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 510, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.savePhoto)
        self.layout_tab1.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 510, 191, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.setDefaultLocation)
        self.layout_tab1.addWidget(self.pushButton_3)

        self.pushButton_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 510, 141, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.calibration.calibrateCamera)
        self.layout_tab2.addWidget(self.pushButton_4)

        self.label2 = QtWidgets.QLabel(self.tab2)
        self.label2.setGeometry(QtCore.QRect(30, 30, 581, 431))
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap("Pose_Image.jpg"))
        self.label2.setObjectName("label2")
        self.layout_tab2.addWidget(self.label2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.filename = 'Snapshot ' + str(time.strftime("%Y-%b-%d at %H.%M.%S %p")) + '.png'
        self.tmp = None
        self.brightness_value_now = 0
        self.blur_value_now = 0
        self.fps = 0
        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.brightness_value)
        self.horizontalSlider_2.valueChanged['int'].connect(self.blur_value)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Process"))
        self.pushButton_2.setText(_translate("MainWindow", "Snap"))
        self.pushButton_3.setText(_translate("MainWindow", "Save Location"))
        self.pushButton_4.setText(_translate("MainWindow", "Calibrate"))
        self.checkBox.setText(_translate("MainWindow", "Show Labels"))

    def startCameraWithoutLabels(self):
        self.stopEvent = threading.Event()
        self.camera_thread = threading.Thread(target=self.CameraWithoutLabels)
        self.camera_thread.daemon = True
        self.camera_thread.start()
    def startCameraWithLabels(self):
        self.stopEvent = threading.Event()
        self.camera_thread = threading.Thread(target=self.CameraWithLabels)
        self.camera_thread.daemon = True
        self.camera_thread.start()
    def changeCameraSetting(self):
        self.stopEvent.set()
        if self.checkBox.isChecked():
            self.isLabel = True
            self.startCameraWithLabels()
        else:
            self.isLabel = False
            self.startCameraWithoutLabels()
    def detect_pose(self,image, camera_matrix, dist_coeffs):
        # Undistort the image
        undistorted_image = cv2.undistort(image, camera_matrix, dist_coeffs)

    

        # Detect markers in the undistorted image
        marker_corners, marker_ids, _ = cv2.aruco.detectMarkers(undistorted_image, self.dictionary, parameters=self.params)

        # If at least one marker is detected
        if len(marker_ids) > 0:
            # Interpolate CharUco corners
            charuco_retval, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(marker_corners, marker_ids, undistorted_image, self.board)

            # If enough corners are found, estimate the pose
            if charuco_retval:
                retval, rvec, tvec = cv2.aruco.estimatePoseCharucoBoard(charuco_corners, charuco_ids, self.board, camera_matrix, dist_coeffs, None, None)

                # If pose estimation is successful, draw the axis
                if retval:
                    cv2.drawFrameAxes(undistorted_image, camera_matrix, dist_coeffs, rvec, tvec, length=0.1, thickness=15)
        return undistorted_image
    def CameraWithLabels(self):
        print("Camera With Labels")
        i = 0
        while self.vid.isOpened() and self.isLabel:
            all_charuco_corners = []
            all_charuco_ids = []
            _, frame = self.vid.read()
            if _:
                self.image = frame.copy()
                gray = cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)
                image_copy = gray.copy()
                marker_corners, marker_ids, _ = cv2.aruco.detectMarkers(gray, self.dictionary, parameters=self.params)
                if len(marker_corners) > 0:
                    image_copy = cv2.aruco.drawDetectedMarkers(self.image, marker_corners, marker_ids)
                    charuco_retval, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(marker_corners, marker_ids, self.image , self.board)
                    if charuco_retval:
                        all_charuco_corners.append(charuco_corners)
                        all_charuco_ids.append(charuco_ids)

                    try:
                        retval, camera_matrix, dist_coeffs, rvecs, tvecs = cv2.aruco.calibrateCameraCharuco(all_charuco_corners,
                                                                                                            all_charuco_ids,
                                                                                                            self.board,
                                                                                                            self.image.shape[:2],
                                                                                                            None, None,
                                                                                                            criteria=self.criteria)
                        cv2.imwrite('Pose_Image.jpg',image_copy)
                        if len(marker_corners)>29:
                            self.buttonFlag.setStyleSheet("background-color : green")
                            i+=1
                            cv2.imwrite(f'Pose_Image_FULL-{i}.jpg',image_copy)
                            print(f"FULL {i}th image")
                        else:
                            self.buttonFlag.setStyleSheet("background-color : red")
                        print("saved")
                    except:
                          pass

            self.update()
    def CameraWithoutLabels(self):
        print("Camera Without Labels")
        cnt = 0
        frames_to_count = 20
        st = 0
        fps = 0
        
        while (self.vid.isOpened() and not self.isLabel):
            ret,frame = self.vid.read()
            if ret:
                self.image = frame
            #self.image = imutils.resize(self.image,width=1920,height=1080)
                self.update()
                key = cv2.waitKey(1) & 0xFF
                if key == ord("q"):
                    break
        
    def setPhoto(self,image):
        """ This function will take image input and resize it 
            only for display purpose and convert it to QImage
            to set at the label.
        """
        self.tmp = image
        image = imutils.resize(image,width=640)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        height, width, channel = frame.shape
        bytesPerLine = 3 * width
        self.qImg = QImage(frame.data, width, height, bytesPerLine, QImage.Format_RGB888)
        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.label.setPixmap(QtGui.QPixmap.fromImage(self.qImg))
        self.label2.setPixmap(QtGui.QPixmap("Pose_Image_FULL.jpg"))

    def brightness_value(self, value):
        """ This function will take value from the slider
            for the brightness from 0 to 99
        """
        self.brightness_value_now = value
        print('Brightness: ', value)
        self.update()  # Update displayed image

    def blur_value(self, value):
        """ This function will take value from the slider 
            for the blur from 0 to 99
        """
        self.blur_value_now = value
        print('Blur: ', value)
        self.update()  # Update displayed image


    def changeBrightness(self,img,value):
        """ This function will take an image (img) and the brightness
            value. It will perform the brightness change using OpenCv
            and after split, will merge the img and return it.
        """
        hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
        h,s,v = cv2.split(hsv)
        lim = 255 - value
        v[v>lim] = 255
        v[v<=lim] += value
        final_hsv = cv2.merge((h,s,v))
        img = cv2.cvtColor(final_hsv,cv2.COLOR_HSV2BGR)
        return img
    
    def applyFilter(self):
        selected_filter = self.comboBox.currentText()
        if selected_filter == "Gaussian Blur":
            self.blur_value(self.blur_value_now)  # Apply Gaussian blur
        elif selected_filter == "Bilateral Filter":
            self.bilateral_filter(self.blur_value_now)  # Apply bilateral filter

    def bilateral_filter(self, value):
        img = self.image
        img = cv2.bilateralFilter(img, 3, value, value)
        self.update_image(img)

    def update_image(self, img):
        frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        height, width, channel = frame.shape
        bytesPerLine = 3 * width
        self.qImg = QImage(frame.data, width, height, bytesPerLine, QImage.Format_RGB888)
        self.label.setPixmap(QtGui.QPixmap.fromImage(self.qImg))
        
    def changeBlur(self,img,value):
        kernel_size = (value+1,value+1) # +1 is to avoid 0
        img = cv2.blur(img,kernel_size)
        return img

    def update(self):
        img = self.image.copy()
        img = self.changeBrightness(self.image,self.brightness_value_now)
        img = self.changeBlur(img,self.blur_value_now)
        self.setPhoto(img)

    def savePhoto(self):
        """ This function will save the original frame without any modifications"""
        self.filename = 'Snapshot '+str(time.strftime("%Y-%b-%d at %H.%M.%S %p"))+'.png'
        cv2.imwrite(self.default_folder+self.filename, self.image)
        
        print('Image saved as:', self.filename)
    def setDefaultLocation(self):
        self.default_folder = QFileDialog.getExistingDirectory(None, "Select Default Save Location", QtCore.QDir.homePath()) + "/"
        print(self.default_folder)
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    #ui.vid = cv2.VideoCapture('rtsp://172.24.45.61:8080/h264_ulaw.sdp')
    ui.vid = cv2.VideoCapture(0)
    ui.startCameraWithoutLabels()
    MainWindow.show()
    sys.exit(app.exec_())
